// Trending data — updated daily by /update-trending skill
// History keeps the last 30 daily snapshots.
// Game fields: { name, score, mentions, sources, change, bgg, img }
//   bgg  — full BGG URL (null if unknown)
//   img  — square thumbnail URL (null if unknown; skill populates these)
//   change — rank delta vs prior snapshot (+up, -down, 0 same, null new)

const TRENDING_DATA = {
  meta: {
    subreddits: ["r/boardgames", "r/soloboardgaming", "r/boardgamescirclejerk"],
  },
  history: [
    {
      date: "2026-06-14",
      overall: [
        { name: "Mansions of Madness",         score: 567, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/205059/mansions-of-madness-second-edition", img: "https://cf.geekdo-images.com/LIooA9bTdjnE9qmhjL-UFw__square200/img/I60Uk2oPsbiV0u_onRxI6HNgUxc=/200x200/filters:strip_icc()/pic3118622.jpg" },
        { name: "Death May Die",                score: 160, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/253344/cthulhu-death-may-die",               img: "https://cf.geekdo-images.com/e8D09pfFsUsoX1D81EeoZg__square200/img/afb-GccHuMdWSvKumas7GSfmzUk=/200x200/filters:strip_icc()/pic4705171.jpg" },
        { name: "Vantage",                      score: 153, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/420033/vantage",                             img: "https://cf.geekdo-images.com/M0e9l-SHH2H4RMSAcnsDgg__square200/img/AFfSFufAeHUbnKONFYGAZO7VIMs=/200x200/filters:strip_icc()/pic8658546.jpg" },
        { name: "Tiny Epic Galaxies",           score: 122, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/163967/tiny-epic-galaxies",                  img: "https://cf.geekdo-images.com/c_87h8o0AOrfCO3hxMjjrA__square200/img/agIZRVZrHXMq9yQvCqX4GxkiL1c=/200x200/filters:strip_icc()/pic2349732.jpg" },
        { name: "Earthborne Rangers",           score: 119, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/342900/earthborne-rangers",                  img: "https://cf.geekdo-images.com/EVfMwPiHmxDUvY32BbghBg__square200/img/BzfEEBzbXRa1lHm-5dc3ls6wuHU=/200x200/filters:strip_icc()/pic7378384.jpg" },
        { name: "Root",                         score:  94, mentions: 3, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/237182/root",                               img: "https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__square200/img/pKGjK1ToJcM3DyOYnc2LHdhkKJ4=/200x200/filters:strip_icc()/pic4254509.jpg" },
        { name: "Finspan",                      score:  86, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/436126/finspan",                            img: "https://cf.geekdo-images.com/BBefMnVYBDS3EbJ9fPaC8A__square200/img/cEPH6iUO-LzfKPpSVUSfnZBiwbM=/200x200/filters:strip_icc()/pic8634453.jpg" },
        { name: "Wingspan",                     score:  83, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/266192/wingspan",                           img: "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__square200/img/BuUGdo8iEnHLPKZvyttszIdBNOU=/200x200/filters:strip_icc()/pic4458123.jpg" },
        { name: "Gloomhaven: Jaws of the Lion", score:  77, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",         img: "https://cf.geekdo-images.com/_HhIdavYW-hid20Iq3hhmg__square200/img/PAvcImUWC1c5q2TBIbG87fyPfEM=/200x200/filters:strip_icc()/pic5055631.jpg" },
        { name: "Twilight Imperium 4",          score:  74, mentions: 2, sources: ["r/boardgamescirclejerk"], change: null, bgg: "https://boardgamegeek.com/boardgame/233078/twilight-imperium-fourth-edition",    img: "https://cf.geekdo-images.com/_Ppn5lssO5OaildSE-FgFA__square200/img/VWIKhG2w7Bwh7PX7_xHRSmf6s6c=/200x200/filters:strip_icc()/pic3727516.jpg" },
        { name: "Barbarian Prince",             score:  65, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/3392/barbarian-prince",                     img: "https://cf.geekdo-images.com/NlBbux6DGwuSizHalTg1xA__square200/img/o9c44aGF66xNOigqam-sXC-SpeA=/200x200/filters:strip_icc()/pic8536.jpg" },
        { name: "Kemet",                        score:  60, mentions: 4, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/127023/kemet",                              img: "https://cf.geekdo-images.com/RmZjhy7_6REp8IaXh9Zqwg__square200/img/0USgPWRmHdqDv0CnAOv0jfN3Ms0=/200x200/filters:strip_icc()/pic3979527.jpg" },
        { name: "Inis",                         score:  55, mentions: 3, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/155821/inis",                               img: "https://cf.geekdo-images.com/6QE8mnPFmauoj2THsyUYPA__square200/img/2ALp_8882peIDCPTqNowenNyvmA=/200x200/filters:strip_icc()/pic4739757.jpg" },
        { name: "Trailblazers",                 score:  55, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/365421/trailblazers",                       img: "https://cf.geekdo-images.com/eHfbmoBZU-lfqSTAXCdbPA__square200/img/bbjMFhqAxBYIIZfqK7n8R1Pj3wA=/200x200/filters:strip_icc()/pic6925280.jpg" },
        { name: "Storyfold: Wildwoods",         score:  52, mentions: 1, sources: ["r/soloboardgaming"],      change: null, bgg: "https://boardgamegeek.com/boardgame/425505/storyfold-wildwoods",                img: "https://cf.geekdo-images.com/s8nB_bnCj_nBdwMJZqsptA__square200/img/0dT9LLAJSC0oz_KYUfp9rr44sck=/200x200/filters:strip_icc()/pic8332322.png" },
      ],
      solo: [
        { name: "Vantage",                      score: 153, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/420033/vantage",                             img: "https://cf.geekdo-images.com/M0e9l-SHH2H4RMSAcnsDgg__square200/img/AFfSFufAeHUbnKONFYGAZO7VIMs=/200x200/filters:strip_icc()/pic8658546.jpg" },
        { name: "Tiny Epic Galaxies",           score: 122, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/163967/tiny-epic-galaxies",                  img: "https://cf.geekdo-images.com/c_87h8o0AOrfCO3hxMjjrA__square200/img/agIZRVZrHXMq9yQvCqX4GxkiL1c=/200x200/filters:strip_icc()/pic2349732.jpg" },
        { name: "Earthborne Rangers",           score: 119, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/342900/earthborne-rangers",                  img: "https://cf.geekdo-images.com/EVfMwPiHmxDUvY32BbghBg__square200/img/BzfEEBzbXRa1lHm-5dc3ls6wuHU=/200x200/filters:strip_icc()/pic7378384.jpg" },
        { name: "Gloomhaven: Jaws of the Lion", score:  77, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",         img: "https://cf.geekdo-images.com/_HhIdavYW-hid20Iq3hhmg__square200/img/PAvcImUWC1c5q2TBIbG87fyPfEM=/200x200/filters:strip_icc()/pic5055631.jpg" },
        { name: "Barbarian Prince",             score:  65, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/3392/barbarian-prince",                     img: "https://cf.geekdo-images.com/NlBbux6DGwuSizHalTg1xA__square200/img/o9c44aGF66xNOigqam-sXC-SpeA=/200x200/filters:strip_icc()/pic8536.jpg" },
        { name: "Trailblazers",                 score:  55, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/365421/trailblazers",                       img: "https://cf.geekdo-images.com/eHfbmoBZU-lfqSTAXCdbPA__square200/img/bbjMFhqAxBYIIZfqK7n8R1Pj3wA=/200x200/filters:strip_icc()/pic6925280.jpg" },
        { name: "Storyfold: Wildwoods",         score:  52, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/425505/storyfold-wildwoods",                img: "https://cf.geekdo-images.com/s8nB_bnCj_nBdwMJZqsptA__square200/img/0dT9LLAJSC0oz_KYUfp9rr44sck=/200x200/filters:strip_icc()/pic8332322.png" },
        { name: "Everdell: Silverfrost",        score:  42, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/199792/everdell",                           img: "https://cf.geekdo-images.com/fjE7V5LNq31yVEW_yuqI-Q__square200/img/oSGR0N6s84_G6q5MSCrZ1ILL7VE=/200x200/filters:strip_icc()/pic3918905.png" },
        { name: "Judge Dredd: Helter Skelter",  score:  31, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/275034/judge-dredd-helter-skelter",          img: "https://cf.geekdo-images.com/voQGyVEKCWsh-EfbjdnDCA__square200/img/TCR9suSvnYCRaEEZ2q9eOYc58CM=/200x200/filters:strip_icc()/pic4973077.jpg" },
        { name: "Ambush!",                      score:  29, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/1608/ambush",                               img: "https://cf.geekdo-images.com/8H-hiPuWsdD07fcj0kMsYA__square200/img/vFrWFOBxNFKEVG4WhC9lMrIOIh8=/200x200/filters:strip_icc()/pic265524.jpg" },
        { name: "Ark Nova / Sanctuary",         score:  29, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/342942/ark-nova",                           img: "https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__square200/img/bHhp_JlkP0JfeHgVd7bzt8W510k=/200x200/filters:strip_icc()/pic6293412.jpg" },
        { name: "Imperium Classics",            score:  26, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/318184/imperium-classics",                  img: "https://cf.geekdo-images.com/MN0OvKejfrfwD6bupQHp4g__square200/img/0Nh58B0-AtVBgnejOt4HxLneKVM=/200x200/filters:strip_icc()/pic5623566.jpg" },
        { name: "Hadrian's Wall",               score:  18, mentions: 3, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/304783/hadrians-wall",                      img: "https://cf.geekdo-images.com/4XzRDw3VrgNpNfZlzZl66w__square200/img/XjeEtL3mWkGPSMQdwaaRZoId-Zk=/200x200/filters:strip_icc()/pic5608818.png" },
        { name: "Final Girl",                   score:  14, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/277659/final-girl",                         img: "https://cf.geekdo-images.com/TUtzY-F7gKTIKm9y8e1AQw__square200/img/ElsynU1BFxm4xjLFXLp-KtJnQXw=/200x200/filters:strip_icc()/pic6520382.jpg" },
        { name: "Cascadia",                     score:  12, mentions: 2, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/295947/cascadia",                           img: "https://cf.geekdo-images.com/MjeJZfulbsM1DSV3DrGJYA__square200/img/ClDVJ5N-pZlzIkxQBCufbfFXChI=/200x200/filters:strip_icc()/pic5100691.jpg" },
      ],
      party: [
        { name: "SHUG",                    score: 123, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/445698/shug",                img: "https://cf.geekdo-images.com/s-uxgE0xgJO7x3fO4sRK_w__square200/img/fG-ccCPPMTtH-L_kOW2D45HCBvs=/200x200/filters:strip_icc()/pic9202485.jpg", note: "Kickstarter: 12,253 backers" },
        { name: "Blood on the Clocktower", score:  40, mentions: 2, sources: ["r/boardgamescirclejerk"], change: null, bgg: "https://boardgamegeek.com/boardgame/240980/blood-on-the-clocktower", img: "https://cf.geekdo-images.com/HINb2nkFn5IiZxAlzQIs4g__square200/img/FdLq8zXvSnNWo6jw9FusW2s-JJw=/200x200/filters:strip_icc()/pic7009391.jpg" },
        { name: "Codenames",               score:  20, mentions: 2, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/178900/codenames",          img: "https://cf.geekdo-images.com/nC6ifPCDnAItwoKSKXVrnw__square200/img/ZUa-6Wb_m1KmtkAb6MxmcVN6Y50=/200x200/filters:strip_icc()/pic8907965.jpg" },
        { name: "Wavelength",              score:  15, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: "https://boardgamegeek.com/boardgame/262543/wavelength",         img: "https://cf.geekdo-images.com/z4fbPdmJg_5yphJEvql4ZA__square200/img/ojwhvyvB8dMmyzHgEYj5_TxZQ0w=/200x200/filters:strip_icc()/pic4552862.png" },
        { name: "Jackbox Party Pack",      score:  10, mentions: 1, sources: ["r/boardgames"],           change: null, bgg: null,                                                           img: null },
      ],
      crowdfunding: [
        { name: "SHUG",                         backers: 12253, pct: 10044, platform: "Kickstarter", ends: "2026-06-17", url: "https://www.kickstarter.com/projects/shug/shug",                                              bgg: "https://boardgamegeek.com/boardgame/445698/shug",                                  img: "https://cf.geekdo-images.com/s-uxgE0xgJO7x3fO4sRK_w__square200/img/fG-ccCPPMTtH-L_kOW2D45HCBvs=/200x200/filters:strip_icc()/pic9202485.jpg" },
        { name: "Arydia: 2nd Printing",         backers: 11905, pct:  1028, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/far-off-games/arydia-2nd-printing",                          bgg: "https://boardgamegeek.com/boardgame/219650/arydia-the-paths-we-dare-tread",         img: "https://cf.geekdo-images.com/GGXq2lRAJCtS1yPPPmdVKw__square200/img/rNaZEs4MH4yHBFtI2iYYzCSwqc8=/200x200/filters:strip_icc()/pic6205610.png" },
        { name: "Concordia Special Edition",    backers: 11105, pct:  5599, platform: "Gamefound",   ends: "2026-06-30", url: "https://gamefound.com/en/projects/awaken-realms/concordia-special-edition",                   bgg: "https://boardgamegeek.com/boardgame/465819/concordia-special-edition",             img: "https://cf.geekdo-images.com/t09C6AsUI_ApPp1wm6XH-A__square200/img/BT7FL3r7nx-TrgUexKdQqT8PbxQ=/200x200/filters:strip_icc()/pic9437664.jpg" },
        { name: "Zombicide: Dead Men Tales",    backers: 11058, pct:  2063, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/asmodee/dead-men-tales",                                    bgg: "https://boardgamegeek.com/boardgame/463012/zombicide-dead-men-tales",              img: "https://cf.geekdo-images.com/kTHQFpzug4cf0cD7D9jU1Q__square200/img/zUSNLuiR7mR1mLdNo2vJ5b0QpfQ=/200x200/filters:strip_icc()/pic9361421.jpg" },
        { name: "Altera",                       backers:  3181, pct:  1004, platform: "Gamefound",   ends: "2026-06-29", url: "https://gamefound.com/en/projects/iv-studio/altera",                                          bgg: "https://boardgamegeek.com/boardgame/469367/altera",                                img: "https://cf.geekdo-images.com/9kAYghog7T5qu6yMVLsvbQ__square200/img/9sr1jGqcgbRqR0L9Rcx7n4z93mU=/200x200/filters:strip_icc()/pic9544023.png" },
        { name: "Earthborne Trailblazer",       backers:  3178, pct:   311, platform: "Kickstarter", ends: "2026-06-16", url: "https://www.kickstarter.com/projects/earthbornegames/earthborne-trailblazer",                 bgg: "https://boardgamegeek.com/boardgame/469532/earthborne-trailblazer",                img: "https://cf.geekdo-images.com/r_nyI9ng8aMRNk6k5XsJPA__square200/img/LH3eyqaWj0renLlkA8ZUL83twBU=/200x200/filters:strip_icc()/pic9593360.jpg" },
        { name: "8 Dragons",                    backers:  2661, pct:  2611, platform: "Kickstarter", ends: "2026-07-06", url: "https://www.kickstarter.com/projects/wonderbowgames/8-dragons",                               bgg: "https://boardgamegeek.com/boardgame/454438/8-dragons",                             img: "https://cf.geekdo-images.com/R5iIG_-VyhoDw2kYX-lVdA__square200/img/kvCz8Y_R52_forX5N3Kj4zgpqsQ=/200x200/filters:strip_icc()/pic9108005.jpg" },
        { name: "Dragon Ball Z: The Board Game", backers: 1343, pct:  1463, platform: "Kickstarter", ends: "2026-07-07", url: "https://www.kickstarter.com/projects/lynnvander/dragon-ball-z-the-board-game-saga-0",         bgg: null,                                                                               img: null },
      ],
    }
  ]
};
