// Trending data — updated daily by /update-trending skill
// History keeps the last 30 daily snapshots.
// Game fields: { name, score, mentions, sources, change, bgg, img }
//   bgg  — full BGG URL (null if unknown)
//   img  — square thumbnail URL (null if unknown; skill populates these)
//   change — rank delta vs prior snapshot (+up, -down, 0 same, null new)

const TRENDING_DATA = {
  meta: {
    subreddits: ["r/boardgames", "r/soloboardgaming", "r/boardgamescirclejerk"],
  },
  history: [
    {
      date: "2026-06-14",
      overall: [
        { name: "Mansions of Madness",                       score: 572, mentions: 1, sources: ["r/boardgames"],                          change:   0, bgg: "https://boardgamegeek.com/boardgame/205059/mansions-of-madness-second-edition",                               img: "https://cf.geekdo-images.com/LIooA9bTdjnE9qmhjL-UFw__square200/img/I60Uk2oPsbiV0u_onRxI6HNgUxc=/200x200/filters:strip_icc()/pic3118622.jpg" },
        { name: "Root",                                       score: 235, mentions: 3, sources: ["r/boardgames"],                          change:  +4, bgg: "https://boardgamegeek.com/boardgame/237182/root",                                                                img: "https://cf.geekdo-images.com/JUAUWaVUzeBgzirhZNmHHw__square200/img/pKGjK1ToJcM3DyOYnc2LHdhkKJ4=/200x200/filters:strip_icc()/pic4254509.jpg" },
        { name: "Death May Die",                              score: 174, mentions: 2, sources: ["r/boardgames", "r/soloboardgaming"],      change:  -1, bgg: "https://boardgamegeek.com/boardgame/253344/cthulhu-death-may-die",                                           img: "https://cf.geekdo-images.com/e8D09pfFsUsoX1D81EeoZg__square200/img/afb-GccHuMdWSvKumas7GSfmzUk=/200x200/filters:strip_icc()/pic4705171.jpg" },
        { name: "Vantage",                                    score: 168, mentions: 2, sources: ["r/soloboardgaming"],                      change:  -1, bgg: "https://boardgamegeek.com/boardgame/420033/vantage",                                                           img: "https://cf.geekdo-images.com/M0e9l-SHH2H4RMSAcnsDgg__square200/img/AFfSFufAeHUbnKONFYGAZO7VIMs=/200x200/filters:strip_icc()/pic8658546.jpg" },
        { name: "Ruins: Death Binder",                        score: 126, mentions: 1, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/280984/ruins-death-binder",                                               img: "https://cf.geekdo-images.com/dDCc9j3tJ7x1uTBEFqV89Q__square200/img/D345NBEUwqD_m-rtQLqt3y6RzOk=/200x200/filters:strip_icc()/pic5976004.png" },
        { name: "Earthborne Rangers",                         score: 125, mentions: 1, sources: ["r/soloboardgaming"],                      change:  -1, bgg: "https://boardgamegeek.com/boardgame/342900/earthborne-rangers",                                               img: "https://cf.geekdo-images.com/EVfMwPiHmxDUvY32BbghBg__square200/img/BzfEEBzbXRa1lHm-5dc3ls6wuHU=/200x200/filters:strip_icc()/pic7378384.jpg" },
        { name: "Kemet",                                      score: 120, mentions: 2, sources: ["r/boardgames"],                          change:  +5, bgg: "https://boardgamegeek.com/boardgame/127023/kemet",                                                              img: "https://cf.geekdo-images.com/RmZjhy7_6REp8IaXh9Zqwg__square200/img/0USgPWRmHdqDv0CnAOv0jfN3Ms0=/200x200/filters:strip_icc()/pic3979527.jpg" },
        { name: "Inis",                                       score: 120, mentions: 2, sources: ["r/boardgames"],                          change:  +5, bgg: "https://boardgamegeek.com/boardgame/155821/inis",                                                               img: "https://cf.geekdo-images.com/6QE8mnPFmauoj2THsyUYPA__square200/img/2ALp_8882peIDCPTqNowenNyvmA=/200x200/filters:strip_icc()/pic4739757.jpg" },
        { name: "Tiny Epic Galaxies",                         score: 117, mentions: 1, sources: ["r/soloboardgaming"],                      change:  -5, bgg: "https://boardgamegeek.com/boardgame/163967/tiny-epic-galaxies",                                               img: "https://cf.geekdo-images.com/c_87h8o0AOrfCO3hxMjjrA__square200/img/agIZRVZrHXMq9yQvCqX4GxkiL1c=/200x200/filters:strip_icc()/pic2349732.jpg" },
        { name: "Awaken the Ancients",                        score: 110, mentions: 1, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/468233/awaken-the-ancients",                                              img: "https://cf.geekdo-images.com/y-HnBNLn3IwfaRAVrHRv5w__square200/img/i2kdmDNYPhxjptRfVZ92ZYj5O2M=/200x200/filters:strip_icc()/pic9504970.png" },
        { name: "Gaia Project",                               score: 109, mentions: 2, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/220308/gaia-project",                                                    img: "https://cf.geekdo-images.com/hGWFm3hbMlCDsfCsauOQ4g__square200/img/-B_SCvvRB-Q0_yfCwKgIwhdSLNw=/200x200/filters:strip_icc()/pic5375625.png" },
        { name: "Deep Regrets",                               score: 106, mentions: 1, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/397931/deep-regrets",                                                     img: "https://cf.geekdo-images.com/WUvpRzsNSZgq1gyvjiQcWw__square200/img/6_6jOe3kiTpMAp2UoeYon1hjMh0=/200x200/filters:strip_icc()/pic8156363.jpg" },
        { name: "LotR: Fellowship Trick-Taking Game",         score:  97, mentions: 1, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/429293/the-lord-of-the-rings-the-fellowship-of-the-ring-trick-taking-game", img: "https://cf.geekdo-images.com/uC4N_3kQdoHefNPesAHCzQ__square200/img/cnaVUnY1UIgde_Zm2CAUojQpK_g=/200x200/filters:strip_icc()/pic8437787.png" },
        { name: "Wingspan",                                   score:  93, mentions: 1, sources: ["r/boardgames"],                          change:  -6, bgg: "https://boardgamegeek.com/boardgame/266192/wingspan",                                                          img: "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__square200/img/BuUGdo8iEnHLPKZvyttszIdBNOU=/200x200/filters:strip_icc()/pic4458123.jpg" },
        { name: "Endeavor: Deep Sea",                         score:  91, mentions: 1, sources: ["r/soloboardgaming"],                      change: null, bgg: "https://boardgamegeek.com/boardgame/367966/endeavor-deep-sea",                                               img: "https://cf.geekdo-images.com/wIbevITv9W79ELP8rEZoKA__square200/img/7BDx8KnThYSPoWphy0Mz06zDeyk=/200x200/filters:strip_icc()/pic6996584.jpg" },
      ],
      solo: [
        { name: "Vantage",                          score: 168, mentions: 2, sources: ["r/soloboardgaming"], change:    0, bgg: "https://boardgamegeek.com/boardgame/420033/vantage",                                                                img: "https://cf.geekdo-images.com/M0e9l-SHH2H4RMSAcnsDgg__square200/img/AFfSFufAeHUbnKONFYGAZO7VIMs=/200x200/filters:strip_icc()/pic8658546.jpg" },
        { name: "Ruins: Death Binder",              score: 126, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/280984/ruins-death-binder",                                                   img: "https://cf.geekdo-images.com/dDCc9j3tJ7x1uTBEFqV89Q__square200/img/D345NBEUwqD_m-rtQLqt3y6RzOk=/200x200/filters:strip_icc()/pic5976004.png" },
        { name: "Earthborne Rangers",               score: 125, mentions: 1, sources: ["r/soloboardgaming"], change:    0, bgg: "https://boardgamegeek.com/boardgame/342900/earthborne-rangers",                                                   img: "https://cf.geekdo-images.com/EVfMwPiHmxDUvY32BbghBg__square200/img/BzfEEBzbXRa1lHm-5dc3ls6wuHU=/200x200/filters:strip_icc()/pic7378384.jpg" },
        { name: "Tiny Epic Galaxies",               score: 117, mentions: 1, sources: ["r/soloboardgaming"], change:   -2, bgg: "https://boardgamegeek.com/boardgame/163967/tiny-epic-galaxies",                                                   img: "https://cf.geekdo-images.com/c_87h8o0AOrfCO3hxMjjrA__square200/img/agIZRVZrHXMq9yQvCqX4GxkiL1c=/200x200/filters:strip_icc()/pic2349732.jpg" },
        { name: "Awaken the Ancients",              score: 110, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/468233/awaken-the-ancients",                                                  img: "https://cf.geekdo-images.com/y-HnBNLn3IwfaRAVrHRv5w__square200/img/i2kdmDNYPhxjptRfVZ92ZYj5O2M=/200x200/filters:strip_icc()/pic9504970.png" },
        { name: "Gaia Project",                     score: 109, mentions: 2, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/220308/gaia-project",                                                        img: "https://cf.geekdo-images.com/hGWFm3hbMlCDsfCsauOQ4g__square200/img/-B_SCvvRB-Q0_yfCwKgIwhdSLNw=/200x200/filters:strip_icc()/pic5375625.png" },
        { name: "Deep Regrets",                     score: 106, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/397931/deep-regrets",                                                        img: "https://cf.geekdo-images.com/WUvpRzsNSZgq1gyvjiQcWw__square200/img/6_6jOe3kiTpMAp2UoeYon1hjMh0=/200x200/filters:strip_icc()/pic8156363.jpg" },
        { name: "LotR: Fellowship Trick-Taking Game", score: 97, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/429293/the-lord-of-the-rings-the-fellowship-of-the-ring-trick-taking-game", img: "https://cf.geekdo-images.com/uC4N_3kQdoHefNPesAHCzQ__square200/img/cnaVUnY1UIgde_Zm2CAUojQpK_g=/200x200/filters:strip_icc()/pic8437787.png" },
        { name: "Endeavor: Deep Sea",               score:  91, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/367966/endeavor-deep-sea",                                                   img: "https://cf.geekdo-images.com/wIbevITv9W79ELP8rEZoKA__square200/img/7BDx8KnThYSPoWphy0Mz06zDeyk=/200x200/filters:strip_icc()/pic6996584.jpg" },
        { name: "Fleet: The Dice Game",             score:  90, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/328326/fleet-the-dice-game-second-edition",                                   img: "https://cf.geekdo-images.com/XbfUcIO4lCp449zLmZ_4_g__square200/img/6v4DX-gSksaBKaaByGy38HSEiIY=/200x200/filters:strip_icc()/pic4460262.jpg" },
        { name: "Gloomhaven: Jaws of the Lion",     score:  86, mentions: 2, sources: ["r/soloboardgaming"], change:   -7, bgg: "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",                                          img: "https://cf.geekdo-images.com/_HhIdavYW-hid20Iq3hhmg__square200/img/PAvcImUWC1c5q2TBIbG87fyPfEM=/200x200/filters:strip_icc()/pic5055631.jpg" },
        { name: "Barbarian Prince",                 score:  62, mentions: 1, sources: ["r/soloboardgaming"], change:   -7, bgg: "https://boardgamegeek.com/boardgame/3392/barbarian-prince",                                                      img: "https://cf.geekdo-images.com/NlBbux6DGwuSizHalTg1xA__square200/img/o9c44aGF66xNOigqam-sXC-SpeA=/200x200/filters:strip_icc()/pic8536.jpg" },
        { name: "Marvel Champions",                 score:  57, mentions: 2, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/285774/marvel-champions-the-card-game",                                        img: "https://cf.geekdo-images.com/kRvUgYiaOq07kC67ZK5UoQ__square200/img/dELqF3Nu63hBEDyV_WbyvsIVAr0=/200x200/filters:strip_icc()/pic4900321.jpg" },
        { name: "Hoplomachus: Victorum",            score:  54, mentions: 1, sources: ["r/soloboardgaming"], change: null, bgg: "https://boardgamegeek.com/boardgame/313889/hoplomachus-victorum",                                                 img: "https://cf.geekdo-images.com/VIfMhlaUvGwtHc4HqKy-jA__square200/img/RLXNA73GLoW1CQ_4SoiIxXzzco8=/200x200/filters:strip_icc()/pic7340742.jpg" },
        { name: "Trailblazers",                     score:  54, mentions: 1, sources: ["r/soloboardgaming"], change:   -9, bgg: "https://boardgamegeek.com/boardgame/365421/trailblazers",                                                         img: "https://cf.geekdo-images.com/eHfbmoBZU-lfqSTAXCdbPA__square200/img/bbjMFhqAxBYIIZfqK7n8R1Pj3wA=/200x200/filters:strip_icc()/pic6925280.jpg" },
      ],
      party: [
        { name: "SHUG",                    score: 30, mentions: 1, sources: ["r/boardgames"],           change:  0, bgg: "https://boardgamegeek.com/boardgame/445698/shug",                img: "https://cf.geekdo-images.com/s-uxgE0xgJO7x3fO4sRK_w__square200/img/fG-ccCPPMTtH-L_kOW2D45HCBvs=/200x200/filters:strip_icc()/pic9202485.jpg" },
        { name: "Blood on the Clocktower", score:  4, mentions: 1, sources: ["r/boardgamescirclejerk"], change:  0, bgg: "https://boardgamegeek.com/boardgame/240980/blood-on-the-clocktower", img: "https://cf.geekdo-images.com/HINb2nkFn5IiZxAlzQIs4g__square200/img/FdLq8zXvSnNWo6jw9FusW2s-JJw=/200x200/filters:strip_icc()/pic7009391.jpg" },
      ],
      crowdfunding: [
        { name: "SHUG",                              backers: 12253, pct:    10044, platform: "Kickstarter", ends: "2026-06-17", url: "https://www.kickstarter.com/projects/shug/shug",                                              bgg: "https://boardgamegeek.com/boardgame/445698/shug",                                                    img: "https://cf.geekdo-images.com/s-uxgE0xgJO7x3fO4sRK_w__square200/img/fG-ccCPPMTtH-L_kOW2D45HCBvs=/200x200/filters:strip_icc()/pic9202485.jpg" },
        { name: "Arydia: 2nd Printing",              backers: 11905, pct:     1028, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/far-off-games/arydia-2nd-printing",                          bgg: "https://boardgamegeek.com/boardgame/219650/arydia-the-paths-we-dare-tread",                           img: "https://cf.geekdo-images.com/GGXq2lRAJCtS1yPPPmdVKw__square200/img/rNaZEs4MH4yHBFtI2iYYzCSwqc8=/200x200/filters:strip_icc()/pic6205610.png" },
        { name: "Concordia Special Edition",         backers: 11105, pct:     5599, platform: "Gamefound",   ends: "2026-06-30", url: "https://gamefound.com/en/projects/awaken-realms/concordia-special-edition",                   bgg: "https://boardgamegeek.com/boardgame/465819/concordia-special-edition",                                img: "https://cf.geekdo-images.com/t09C6AsUI_ApPp1wm6XH-A__square200/img/BT7FL3r7nx-TrgUexKdQqT8PbxQ=/200x200/filters:strip_icc()/pic9437664.jpg" },
        { name: "Zombicide: Dead Men Tales",         backers: 11058, pct:     2063, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/asmodee/dead-men-tales",                                    bgg: "https://boardgamegeek.com/boardgame/463012/zombicide-dead-men-tales",                                 img: "https://cf.geekdo-images.com/kTHQFpzug4cf0cD7D9jU1Q__square200/img/zUSNLuiR7mR1mLdNo2vJ5b0QpfQ=/200x200/filters:strip_icc()/pic9361421.jpg" },
        { name: "Hover",                             backers:  4706, pct:     3656, platform: "Kickstarter", ends: "2026-06-19", url: "https://www.kickstarter.com/projects/victorshiu/hover-a-surprisingly-brutal-hummingbird-game",  bgg: "https://boardgamegeek.com/boardgame/452208/hover",                                                    img: "https://cf.geekdo-images.com/jOtd43CMwUp4QR_g5gGPVg__square200/img/pb5qnpF1t64FjNGL_zIjq1fEmqc=/200x200/filters:strip_icc()/pic9596418.jpg" },
        { name: "Let's Go! To France",               backers:  4006, pct:     3932, platform: "Kickstarter", ends: "2026-06-20", url: "https://www.kickstarter.com/projects/alderac/lets-go-to-france-from-aeg",                      bgg: "https://boardgamegeek.com/boardgame/455256/lets-go-to-france",                                       img: "https://cf.geekdo-images.com/GMK2baMKgw9ivTBf7lXbiw__square200/img/AYKjlxXKgvS_qWwD3j53dhsIOwM=/200x200/filters:strip_icc()/pic9131662.jpg" },
        { name: "Altera",                            backers:  3181, pct:     1004, platform: "Gamefound",   ends: "2026-06-29", url: "https://gamefound.com/en/projects/iv-studio/altera",                                          bgg: "https://boardgamegeek.com/boardgame/469367/altera",                                                   img: "https://cf.geekdo-images.com/9kAYghog7T5qu6yMVLsvbQ__square200/img/9sr1jGqcgbRqR0L9Rcx7n4z93mU=/200x200/filters:strip_icc()/pic9544023.png" },
        { name: "Earthborne Trailblazer",            backers:  3178, pct:      311, platform: "Kickstarter", ends: "2026-06-16", url: "https://www.kickstarter.com/projects/earthbornegames/earthborne-trailblazer",                 bgg: "https://boardgamegeek.com/boardgame/469532/earthborne-trailblazer",                                   img: "https://cf.geekdo-images.com/r_nyI9ng8aMRNk6k5XsJPA__square200/img/LH3eyqaWj0renLlkA8ZUL83twBU=/200x200/filters:strip_icc()/pic9593360.jpg" },
        { name: "Oakspire",                          backers:  2959, pct:     null, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/lucky-duck-games/oakspire",                                 bgg: "https://boardgamegeek.com/boardgame/463976/oakspire-the-builders-of-the-sunleaf-grove",              img: "https://cf.geekdo-images.com/lpwHHoKrcpuCcLyI0h0LhA__square200/img/gwssmovXejOAjGXjDx7VMGmgQy0=/200x200/filters:strip_icc()/pic9386128.png" },
        { name: "Queen Alice",                       backers:  2734, pct:      827, platform: "Gamefound",   ends: null,         url: "https://gamefound.com/en/projects/combo_games/queen-alice",                                   bgg: "https://boardgamegeek.com/boardgame/456236/queen-alice",                                             img: "https://cf.geekdo-images.com/PibSbnnxUse0XwP57AbAfQ__square200/img/OPi8cAUt91wqv6SyAFKhNQxwEeA=/200x200/filters:strip_icc()/pic9160910.jpg" },
        { name: "8 Dragons",                         backers:  2661, pct:     2611, platform: "Kickstarter", ends: "2026-07-06", url: "https://www.kickstarter.com/projects/wonderbowgames/8-dragons",                               bgg: "https://boardgamegeek.com/boardgame/454438/8-dragons",                                               img: "https://cf.geekdo-images.com/R5iIG_-VyhoDw2kYX-lVdA__square200/img/kvCz8Y_R52_forX5N3Kj4zgpqsQ=/200x200/filters:strip_icc()/pic9108005.jpg" },
        { name: "Stonesaga: Second Printing",        backers:  2109, pct:      775, platform: "Gamefound",   ends: "2026-06-20", url: "https://gamefound.com/en/projects/oomm-games/stonesaga-second-printing",                      bgg: "https://boardgamegeek.com/boardgame/356944/stonesaga",                                               img: "https://cf.geekdo-images.com/AdQyAm_1faLFy74I465xBA__square200/img/miTmPOdRHb0lM-p8wbDx51_moGM=/200x200/filters:strip_icc()/pic6685693.jpg" },
        { name: "Exquisite Corpses: The Game",       backers:  1867, pct:      456, platform: "Kickstarter", ends: "2026-06-15", url: "https://www.kickstarter.com/projects/tinyonion/exquisite-corpses-the-game",                    bgg: null,                                                                                                  img: null },
        { name: "Notebook Nations",                  backers:  1724, pct: 13556000, platform: "Kickstarter", ends: "2026-06-18", url: "https://www.kickstarter.com/projects/dsminervastudio/notebook-nations",                        bgg: "https://boardgamegeek.com/boardgame/447130/notebook-nations",                                        img: "https://cf.geekdo-images.com/lRHWg4MH81DlpT1s3WO9Bw__square200/img/y0pWCF8eyOZxNN_w1mVXa_JyKQU=/200x200/filters:strip_icc()/pic9036018.png" },
        { name: "Die in the Dungeon: The Board Game",backers:  1361, pct:      511, platform: "Kickstarter", ends: "2026-06-19", url: "https://www.kickstarter.com/projects/roomizgames/die-in-the-dungeon-the-board-game",           bgg: "https://boardgamegeek.com/boardgame/462623/die-in-the-dungeon-the-board-game",                       img: "https://cf.geekdo-images.com/wvj10uA5basMYW5YRN3feQ__square200/img/-Lx418HIAV10Ykqh6WVeLHBAQzc=/200x200/filters:strip_icc()/pic9353245.jpg" },
        { name: "Dragon Ball Z: The Board Game Saga",backers:  1343, pct:     1463, platform: "Kickstarter", ends: "2026-07-07", url: "https://www.kickstarter.com/projects/lynnvander/dragon-ball-z-the-board-game-saga-0",         bgg: null,                                                                                                  img: null },
      ],
    }
  ]
};
